version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: manikanth1709/mean-backend:latest
    container_name: mean-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: always

  frontend:
    image: manikanth1709/mean-frontend:latest
    container_name: mean-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
